// Map of all applications and their configurations
// This module was initially generated by mano/scripts/generate-apps-conf

'use strict';

module.exports = {
	"apps/business-process-submitted": require("../../apps/business-process-submitted/mano"),
	"apps/meta-admin": require("../../apps/meta-admin/mano"),
	"apps/public": require("../../apps/public/mano"),
	"apps/user": require("../../apps/user/mano"),
	"apps/users-admin": require("../../apps/users-admin/mano")
};
