// List of all applications
// This module was initially generated by mano/scripts/generate-apps-list

'use strict';

module.exports = [
	"apps/business-process-submitted",
	"apps/meta-admin",
	"apps/public",
	"apps/user",
	"apps/users-admin"
];
